name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    env:
      Solution_Name: 'Code Projects.sln'
      Test_Project_Path: 'C:\Users\isaac\RiderProjects\NEA-AI-Game\Code Projects.csproj'
      Wap_Project_Directory: 'C:\Users\isaac\RiderProjects\NEA-AI-Game\WapProjectDir'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Build the application
      run: dotnet build $env:Solution_Name /p:Configuration=$env:Configuration
      env:
        API_KEY: ${{ secrets.API_KEY }}
        Configuration: ${{ matrix.configuration }}
        
#    - name: Test the application
#      run: dotnet test --no-build $env:Test_Project_Path
#      env:
#        API_KEY: ${{ secrets.API_KEY }}
